
# buld phase
FROM node:20-slim AS build

WORKDIR /app

COPY ./dashboard/package*.json ./

RUN npm install -g pnpm
RUN pnpm install

COPY ./dashboard .

RUN npm run build


# run phase
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]